app:
  name:
  port:

db:
  host:
  username:
  password:
  database:

redis:
  host:
  port:
  user:
  pass:

jwt:
  cookieName:
  verify:
    issuer:
    audience:

swagger:
  enable: true

microservice:
  server:
    transport:
    options:
      servers:
  clients:
    ucenter:
      transport:
      options:
        servers:
