app:
  name:
  port:

db:
  host:
  username:
  password:
  database:

redis:
  host:
  port:
  user:
  pass:

cors:
  origins:
    - 'http://127.0.0.1:8000'

jwt:
  cookieName:
  verify:
    issuer:
    audience:

swagger:
  enable: true

microservice:
  server:
    transport:
    options:
      servers:
  clients:
    ucenter:
      transport:
      options:
        servers:
    network:
      transport:
      options:
        servers:
provider:
  dns:
    type:
    cloudflare:
      token:
      zone-id:
  publisher:
    github:
      https_enfored:
      update-domain-name:
        timeouts:
          - 30000
          - 300000
          - 600000

task:
  processor:
    # Docker processor config
    docker:
      env:
        logging:
          level: debug
        backend:
          #  'Meta-CMS-BE' server url
          url:
        loki:
          # Loki server url
          url: host.docker.internal:3100
        # For decompressing archived files
        7zip:
          bin-name: 7zz
      volumes:
        # Mounts the volume into the /tmp in the container. For example: /var/docker/meta-cms-workspaces
        tmp:
      # Gabbage collection
      gc:
        # Volume /tmp
        tmp:
          # Set to true for a dry run, meaning it does not delete anything but returns a JSON of files/directories it would have deleted
          dry-run: false
          # Files and directories whose age (in seconds) is above this value will be deleted
          max-age: 604800
    mock:
      # mock progresss
      progress:
        - value: 5
          timeout: 200
        - value: 20
          timeout: 1000
        - value: 66
          timeout: 2000
      # Success rate of completing task steps
      success-rate: 0.9
      timeout: 2500
  worker:
    git:
      # BullModuleOptions
      queue:
        limiter:
          max: 5
          duration: 2000
      processor:
        type: DOCKER
        docker:
          image: 'meta-cms-worker-git:0.0.3'
          app:
            name: meta-cms-worker-git
    hexo:
      # BullModuleOptions
      queue:
        limiter:
          max: 10
          duration: 2000
      processor:
        type: DOCKER
        docker:
          image: 'meta-cms-worker-hexo:0.0.3'
          app:
            name: meta-cms-worker-hexo
  workspace:
    lock:
      ttl: 60

post:
  preprocessor:
    urlprefix:
meta-space:
  # camelCase. see MetaWorker.Info.Gateway
  gateway:
    ipfs:
      baseUrl:
